---
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wanglihe2010/finalCaseStudy-config-server
          search-paths: shopping
          default-label: h2DatabaseConfig
server.port: 8888